import { useMemo } from 'react'
import { Badge, C, Progress, StatCard } from './shared'

function riskColor(device) {
  if (device.severity === 'CRITICAL') return C.critical
  if (device.severity === 'HIGH') return C.red
  if (device.severity === 'MEDIUM') return C.amber
  return C.green
}

const EDGES = [['D1','D2'],['D2','D3'],['D1','D4'],['D4','D5'],['D5','D6'],['D3','D6'],['D2','D5']]
const LEGEND = [
  ['normal', 'Normal', 'green'],
  ['suspicious', 'Medium / suspicious', 'amber'],
  ['critical', 'High / critical', 'red'],
  ['sanitizing', 'Sanitizing / verifying', 'teal'],
  ['honeypot', 'Honeypot (decoy)', 'purple'],
]
// Node color is derived only from the device's own live fields (status +
// severity) -- never from the alerts queue, which is intentionally "sticky"
// (an alert stays visible until an operator resolves it, even after the
// device's live reading recovers, see NodeManager.check_alerts). Mixing
// that sticky queue into the topology color made recovered devices keep
// showing red on the map long after their own badge already said Low.
function nodeColor(device){if(device.type==='Honeypot')return C.purple;if(device.status==='isolated'||device.status==='compromised')return C.red;if(device.status==='sanitizing'||device.status==='health_check')return C.teal;if(device.status==='ready_reconnect')return C.green;if(device.severity==='CRITICAL'||device.severity==='HIGH')return C.red;if(device.severity==='MEDIUM')return C.amber;return C.green}

export default function Dashboard({ devices=[], alerts=[], fl, dataset, mqttBroker, attackTypes, triggerHoneypot, replayAttack, setSelDevice }) {
  const real=devices.filter(d=>d.type!=='Honeypot'); const healthy=real.filter(d=>!d.isIsolated&&d.severity==='LOW').length; const highRisk=real.filter(d=>['HIGH','CRITICAL'].includes(d.severity)).length; const attackVisible=real.filter(d=>d.attackType); const firstAttackable=real.find(d=>!d.isIsolated&&(attackTypes?.[d.dataset]||[]).length>0); const firstAttackType=firstAttackable?attackTypes[firstAttackable.dataset]?.[0]:null; const avgRisk=useMemo(()=>real.length?real.reduce((s,d)=>s+Number(d.riskScore||0),0)/real.length:0,[real])
  const demo = Boolean(dataset?.demoFallback)
  return <div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(155px,1fr))',gap:8,marginBottom:12}}><StatCard label="Healthy devices" value={healthy} unit={`/${real.length}`} color={C.green}/><StatCard label="High / critical" value={highRisk} color={highRisk?C.red:C.green} sub="Measured risk"/><StatCard label="Average risk" value={avgRisk.toFixed(1)} unit="/100" color={avgRisk>=50?C.red:avgRisk>=25?C.amber:C.green} sub="Across visible devices"/><StatCard label="FL accuracy" value={fl?.measured?Number(fl.accuracy).toFixed(1):'—'} unit={fl?.measured?'%':''} color={C.accent} sub={fl?`Round ${fl.round}`:'Waiting for measured evaluation'}/></div>
    <div style={{display:'grid',gridTemplateColumns:'1.2fr .8fr',gap:10,marginBottom:12}}><div style={{padding:12,background:C.panel,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{fontSize:12,fontWeight:700}}>Data pipeline</div><div style={{marginTop:9,display:'grid',gap:6,fontSize:10}}>{[['Dataset',dataset?.source||'Loading',dataset?.totalRows?`${dataset.totalRows.toLocaleString()} imported rows`:'' ],['Database','SQLite telemetry store','Same runtime records feed replay + audit'],['ML','Local Isolation Forest','Model scores telemetry without using ground-truth labels'],['MQTT',mqttBroker?.connected?'Connected to Mosquitto':'Not connected',mqttBroker?.connected?`${mqttBroker.host}:${mqttBroker.port}`:'Messages are recorded to SQLite only']].map(([k,v,d])=><div key={k} style={{display:'grid',gridTemplateColumns:'70px 1fr auto',gap:8,padding:'6px 0',borderBottom:`1px solid ${C.border}`}}><span style={{color:C.tm}}>{k}</span><span>{v}</span><span style={{color:C.tm}}>{d}</span></div>)}</div></div><div style={{padding:12,background:C.panel,border:`1px solid ${C.border}`,borderRadius:10}}><div style={{fontSize:12,fontWeight:700}}>Risk policy</div>{[['LOW','0–24.99',C.green],['MEDIUM','25–49.99',C.amber],['HIGH','50–74.99',C.red],['CRITICAL','75–100',C.critical]].map(([n,r,c])=><div key={n} style={{display:'flex',justifyContent:'space-between',padding:'5px 0',borderBottom:`1px solid ${C.border}`,fontSize:10}}><span style={{color:c}}>{n}</span><span style={{color:C.ts}}>{r}</span></div>)}<div style={{marginTop:8,color:C.tm,fontSize:9,lineHeight:1.5}}>Thresholds are operational policy boundaries, not probabilities.</div></div></div>
    <div style={{background:C.panel,border:`1px solid ${C.border}`,borderRadius:11,overflow:'hidden',marginBottom:12}}><div style={{padding:'10px 12px',borderBottom:`1px solid ${C.border}`,display:'flex',justifyContent:'space-between'}}><span style={{fontSize:12,fontWeight:700}}>Live device topology</span><span style={{color:C.tm,fontSize:10}}>{real.length} devices · {devices.filter(d=>d.type==='Honeypot').length} honeypots</span></div><svg viewBox="0 0 100 100" style={{width:'100%',height:285}}>{EDGES.map(([a,b])=>{const x=devices.find(d=>d.id===a);const y=devices.find(d=>d.id===b);return x?.position&&y?.position?<line key={`${a}-${b}`} x1={x.position.x} y1={x.position.y} x2={y.position.x} y2={y.position.y} stroke={C.borderB} strokeWidth=".5" strokeDasharray="2,1.5"/>:null})}{devices.map(d=>d.position?<g key={d.id} onClick={()=>setSelDevice(d)} style={{cursor:'pointer'}}><circle cx={d.position.x} cy={d.position.y} r={d.type==='Honeypot'?2.5:3.4} fill={`${nodeColor(d)}20`} stroke={nodeColor(d)} strokeWidth=".8" strokeDasharray={d.type==='Honeypot'?'1.5,1':undefined}/><text x={d.position.x} y={d.position.y+7} textAnchor="middle" fill={C.ts} fontSize="2.4" fontFamily="monospace">{d.name}</text></g>:null)}</svg><div style={{display:'flex',flexWrap:'wrap',gap:'6px 16px',padding:'8px 12px',borderTop:`1px solid ${C.border}`}}>{LEGEND.map(([key,label,colorKey])=><div key={key} style={{display:'flex',alignItems:'center',gap:5,fontSize:9,color:C.tm}}><span style={{width:8,height:8,borderRadius:99,background:C[colorKey],flexShrink:0,border:key==='honeypot'?`1.5px dashed ${C[colorKey]}`:undefined,boxSizing:'border-box'}}/>{label}</div>)}</div></div>
    <div style={{padding:12,background:C.card,border:`1px solid ${C.border}`,borderRadius:10,marginBottom:12}}><div style={{fontSize:12,fontWeight:700,marginBottom:8}}>Controlled attack demonstration</div><div style={{color:C.ts,fontSize:10,lineHeight:1.6,marginBottom:9}}>{demo?'Offline integration mode: the demo replays deterministic local attack rows through the same ML → risk → alert → quarantine path. These rows are clearly labelled demo telemetry, not ToN-IoT benchmark data.':'The demo replays an actual labeled attack row from the imported ToN-IoT benchmark through the same ML → risk → alert → quarantine path.'}</div><div style={{display:'flex',gap:7,flexWrap:'wrap'}}><button onClick={()=>firstAttackable&&replayAttack(firstAttackable.id,firstAttackType)} disabled={!firstAttackable} style={{padding:'8px 10px',borderRadius:7,cursor:firstAttackable?'pointer':'not-allowed',border:`1px solid ${C.red}66`,background:`${C.red}12`,color:C.red,fontWeight:700,fontSize:10,opacity:firstAttackable?1:0.4}}>Replay first available attack</button><button onClick={triggerHoneypot} style={{padding:'8px 10px',borderRadius:7,cursor:'pointer',border:`1px solid ${C.purple}66`,background:`${C.purple}12`,color:C.purple,fontWeight:700,fontSize:10}}>Controlled honeypot probe</button><span style={{color:C.tm,fontSize:9,alignSelf:'center'}}>{attackVisible.length} device currently carrying attack evidence</span></div></div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:8}}>{real.map(d=><div key={d.id} style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:9,padding:9}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:11,fontWeight:650}}>{d.name}</span><Badge sev={d.severity}/></div><div style={{marginTop:7,display:'flex',justifyContent:'space-between',fontSize:9,color:C.tm}}><span>Risk</span><span style={{color:riskColor(d)}}>{Number(d.riskScore||0).toFixed(1)}</span></div><Progress value={d.riskScore} color={riskColor(d)}/><div style={{marginTop:5,color:C.tm,fontSize:9}}>{d.dataset} · {d.attackType||'normal row'}</div></div>)}</div>
  </div>
}
